// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vdrfdlpwycoghtpqdgvx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZkcmZkbHB3eWNvZ2h0cHFkZ3Z4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ3Mjg0NDAsImV4cCI6MjA1MDMwNDQ0MH0.s3g6GSVN-w4zfSao125iE7jjkRgDslWLhOQ-jHlCh9A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);